import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import matter from 'gray-matter';
import {importContent,readBibliography,parseRIS} from './index.mjs';
import {renderMarkdown,loadContent} from '../../src/content.mjs';
function fixture(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'eularcat-test-'));try{return fn(root);}finally{fs.rmSync(root,{recursive:true,force:true});}}
test('Obsidian and standard image references preserve files with spaces; original Chinese survives',()=>fixture(root=>{const source=path.join(root,'source');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'电路 图.png'),'image bytes');fs.writeFileSync(path.join(source,'note.md'),'---\ntitle: 中文笔记\nlang: zh\nstatus: published\n---\n## 原理\n![[电路 图.png|400]]\n![图](<电路 图.png> "图注")\n中文公式 $V_o=V_i D$。');const result=importContent({root,note:path.join(source,'note.md'),slug:'chinese-note'});const parsed=matter(fs.readFileSync(path.join(result.directory,'index.md'),'utf8'));assert.equal(result.assets,1);assert.match(parsed.content,/\.\/assets\/%E7/);assert.match(parsed.content,/中文公式/);assert.equal(fs.readFileSync(path.join(result.directory,'assets','电路 图.png'),'utf8'),'image bytes');assert.equal(loadContent(root).length,1);assert.match(loadContent(root)[0].html,/katex/);}));
test('missing or ambiguous assets fail before creating output',()=>fixture(root=>{fs.writeFileSync(path.join(root,'note.md'),'![[missing.png]]');assert.throws(()=>importContent({root,note:path.join(root,'note.md'),slug:'missing'}),/Missing asset/);assert.equal(fs.existsSync(path.join(root,'content','notes','missing')),false);for(const dir of ['a','b']){fs.mkdirSync(path.join(root,dir));fs.writeFileSync(path.join(root,dir,'same.png'),'bytes');}fs.writeFileSync(path.join(root,'note.md'),'![[same.png]]');assert.throws(()=>importContent({root,note:path.join(root,'note.md'),slug:'ambiguous'}),/Ambiguous asset/);}));
test('BibTeX, RIS and CSL normalize publication metadata',()=>fixture(root=>{const bib=path.join(root,'paper.bib');fs.writeFileSync(bib,'@article{fixture, title={Importer fixture}, author={Example, Alice and Example, Bob}, year={2024}, journal={Fixture Journal}, doi={10.0000/fixture}}');const b=readBibliography(bib);assert.equal(b.title,'Importer fixture');assert.equal(b.authors.length,2);assert.equal(b.year,2024);const ris=path.join(root,'paper.ris');fs.writeFileSync(ris,'TY  - JOUR\nID  - fixture\nTI  - Importer fixture\nAU  - Alice Example\nAU  - Bob Example\nPY  - 2024/01\nJO  - Fixture Journal\nKW  - COT\nDO  - 10.0000/fixture\nER  - \n');const r=readBibliography(ris);assert.equal(r.year,2024);assert.deepEqual(r.tags,['COT']);assert.equal(r.authors.length,2);const csl=path.join(root,'paper.json');fs.writeFileSync(csl,JSON.stringify([{id:'fixture',title:'CSL fixture',author:[{family:'Example',given:'Alice'}],issued:{'date-parts':[[2025]]}}]));assert.equal(readBibliography(csl).authors[0],'Alice Example');assert.throws(()=>parseRIS('TY  - JOUR\nTI  - incomplete'),/ER/);}));
test('paper import retains metadata and assets; drafts stay unpublished and overwrite is refused',()=>fixture(root=>{fs.writeFileSync(path.join(root,'note.md'),'## 观察\n正文');fs.writeFileSync(path.join(root,'paper.ris'),'TY  - JOUR\nTI  - Fixture paper\nPY  - 2025\nER  - \n');const options={root,note:path.join(root,'note.md'),bibliography:path.join(root,'paper.ris'),type:'reading',slug:'fixture-paper'};const result=importContent(options);assert.equal(result.status,'draft');assert.equal(loadContent(root).length,0);assert.equal(JSON.parse(fs.readFileSync(path.join(result.directory,'metadata.yaml'),'utf8')).year,2025);assert.throws(()=>importContent(options),/already exists/);assert.throws(()=>importContent({...options,slug:'../escape'}),/Slug/);}));
test('renderer handles equations, code, tables, captions, anchors and duplicate headings without raw HTML',()=>{const rendered=renderMarkdown('## 中文标题\n## 中文标题\n\n$$V_o=V_iD$$\n\n```python\nprint("hello")\n```\n\n| A | B |\n|---|---|\n| 1 | 2 |\n\n![图](./assets/figure.png "图注")\n<script>alert(1)</script>');assert.deepEqual(rendered.toc.map(x=>x.id),['中文标题','中文标题-1']);assert.match(rendered.html,/katex/);assert.match(rendered.html,/hljs/);assert.match(rendered.html,/table-scroll/);assert.match(rendered.html,/图注/);assert.doesNotMatch(rendered.html,/<script>/);});
