import {articlesForTopic} from '../learning.mjs';
import {copy} from '../i18n/index.mjs';
import {sectionHeader,escape} from './layout.mjs';
import {icon,aiPreview,readingSkillLink} from './ai.mjs';
export function studioAction(lang,site){const t=copy[lang]; return site.studioUrl?`<a class="button primary" href="${escape(site.studioUrl)}" target="_blank" rel="noopener noreferrer">${t.openStudio}</a>`:`<span class="pending-link">${t.studioPending}</span>`;}
export function noteList(items,lang,empty){const t=copy[lang];return items.length?`<div class="note-list">${items.slice(0,4).map(item=>`<a class="note-row" href="/${item.lang}/${item.type}/${item.slug}/"><div><span class="eyebrow">${item.test?t.testNote:escape(item.category==='engineering'?t.noteCategories[2]:item.type==='reading'?t.nav[1]:t.noteCategories[1])} · ${escape(item.lang.toUpperCase())}</span><h3>${escape(item.title)}</h3><p>${escape(item.description||'')}</p></div><span class="metadata">${escape(item.year||item.date||'')}</span></a>`).join('')}</div>`:`<div class="empty-state"><span class="empty-icon" aria-hidden="true">—</span><p>${empty}</p></div>`;}
export function paperCards(items,lang){const t=copy[lang];return items.length?`<div class="paper-card-grid">${items.slice(0,4).map(item=>`<a class="paper-card" href="/${item.lang}/reading/${item.slug}/"><div class="paper-card-top"><span class="paper-year">${escape(item.year||'')}</span>${icon('reading')}</div><span class="eyebrow">${escape(item.venue||item.journal||'')} · ${item.lang.toUpperCase()}</span><h3>${escape(item.title)}</h3><p>${escape(item.description||'')}</p><span class="paper-open" aria-hidden="true">↗</span></a>`).join('')}</div>`:`<div class="empty-state">${t.emptyReading}</div>`;}
export function learningTiles(lang,site,items=[]){const t=copy[lang];return `<div class="learning-preview">${site.learning.map((group,i)=>{const count=new Set(group.topics.flatMap(topic=>articlesForTopic(items,topic).map(item=>item.type+'/'+item.slug))).size;return `<a href="/${lang}/learn/#${escape(group.category)}" class="learning-column learning-${i}"><span class="tile-glyph" aria-hidden="true">${escape(group.glyph)}<small>${escape(group.code)}</small></span><div><p class="eyebrow">${escape(group.eyebrow)}</p><h3>${escape(group.title[lang])}</h3><p>${escape(group.description[lang])}</p><span class="status ${count?'status-published':''}">${count?`${count} ${lang==='zh'?'篇笔记':count===1?'note':'notes'}`:t.planned}</span></div></a>`;}).join('')}</div>`;}
export function projectPoster(lang,site){const t=copy[lang];return `<div class="project-poster" data-reveal><img src="/assets/studio-poster.webp" width="1586" height="992" alt="${lang==='zh'?'IC Schematics Studio 概念海报':'IC Schematics Studio concept artwork'}" loading="lazy"><div class="poster-copy"><p class="eyebrow">A SMALL TOOL / A CLEARER CIRCUIT</p><h2>IC Schematics<br>Studio</h2><p>${t.studioSummary}</p><div class="project-actions"><a class="button primary" href="/${lang}/projects/ic-schematics-studio/">${t.viewProject}</a>${site.studioUrl?`<a class="button secondary" href="${escape(site.studioUrl)}" target="_blank" rel="noopener noreferrer">${t.openStudio}</a>`:''}</div></div><span class="poster-note">SCHEMATIC ILLUSTRATION / WEB TOOL</span></div>`;}
export function home(lang,site,items=[]){const t=copy[lang];return `
<section class="hero wrap"><div class="hero-grid"><div class="hero-content"><p class="eyebrow">EULARCAT / ENGINEERING NOTEBOOK</p><h1>${t.hero}<br><span>${t.heroAccent}</span></h1><p class="hero-copy">${t.intro}</p><a class="button primary" href="/${lang}/notes/">${t.explore}</a></div><div class="hero-art circuit-papers"><img src="/assets/circuit-papers.webp" width="1536" height="1024" alt="" fetchpriority="high"></div></div><div class="hero-bottom"><span>High-current DC-DC Buck <b>·</b> AI × EDA</span><span class="metadata">LEARNING IN PUBLIC</span></div></section>
<section class="featured-section wrap">${sectionHeader('01',t.featured)}${projectPoster(lang,site)}</section>
<section class="wrap section">${sectionHeader('02',t.learning,t.viewMap,`/${lang}/learn/`)}<p class="section-intro">${t.learningIntro}</p>${learningTiles(lang,site,items)}</section>
<section class="wrap section chapter-notes">${sectionHeader('03',t.recentNotes,t.allNotes,`/${lang}/notes/`)}<p class="section-intro">${t.notesHomeIntro}</p><div class="notes-surface"><div class="notes-intro"><span class="entry-icon">${icon('notes')}</span><p class="eyebrow">PERSONAL NOTEBOOK</p><h3>${t.notesPanelTitle}</h3><p>${t.notesPanelIntro}</p></div>${noteList(items.filter(x=>x.type==='notes'),lang,t.emptyNotes)}</div></section>
<section class="wrap section chapter-reading">${sectionHeader('04',t.recentReading,t.allReading,`/${lang}/reading/`)}<p class="section-intro">${t.readingHomeIntro}</p>${paperCards(items.filter(x=>x.type==='reading'),lang)}${readingSkillLink(lang)}</section>
<section class="wrap section chapter-ai">${sectionHeader('05','AI × IC',t.aiLink,`/${lang}/ai-ic/`)}<p class="section-intro">${t.aiIntro}</p>${aiPreview(lang)}</section>
<section class="wrap about-preview"><img src="/assets/eularcat-mark.png" width="64" height="64" alt="" class="about-mark"><div><p class="eyebrow">ABOUT EULARCAT</p><h2>${t.aboutTitle}</h2><p>${t.aboutIntro}</p><a class="text-link" href="/${lang}/about/">${t.aboutMore}</a></div></section>`;}



