import {articlesForTopic,articlePath} from '../learning.mjs';
import {copy,topicZh} from '../i18n/index.mjs';
import {escape,pageHeader,sectionHeader} from './layout.mjs';
import {workflowGrid,skillCards,readingSkillLink} from './ai.mjs';
import {noteList,studioAction,learningTiles} from './home.mjs';
const topicId=x=>x.toLowerCase().replace(/[^a-z0-9]+/g,'-');
export function learn(lang,site,items){const t=copy[lang];return pageHeader('THE LEARNING ATLAS',t.learning,t.learnPageIntro)+`<div class="wrap page-body">${learningTiles(lang,site,items)}<p class="map-note">${t.statusNote}</p><div class="atlas-groups">${site.learning.map(group=>{return `<section class="map-group" id="${group.category}"><div><span class="atlas-code">${escape(group.code)}</span><h2>${escape(group.title[lang])}</h2><p>${escape(group.description[lang])}</p></div><div class="topic-list">${group.topics.map(topic=>{const articles=articlesForTopic(items,topic);return `<div class="topic-row" id="${topicId(topic)}"><span>${escape(lang==='zh'?topicZh[topic]||topic:topic)}${articles.length?`<span class="topic-notes">${articles.map(item=>`<a href="${articlePath(item)}">${escape(item.title)}</a>`).join('')}</span>`:''}</span><span class="status ${articles.length?'status-published':''}">${articles.length?t.published:t.planned}</span></div>`;}).join('')}</div></section>`;}).join('')}</div>${items.filter(x=>x.type==='learn'&&!x.topic).length?noteList(items.filter(x=>x.type==='learn'&&!x.topic),lang,''):''}</div>`;}
export function library(lang,type,items){const t=copy[lang],papers=type==='reading',records=items.filter(x=>x.type===type);const filters=papers?[t.all,...new Set(records.flatMap(x=>x.tags||[]))]:t.noteCategories;
 return pageHeader(papers?'READING':'NOTES',papers?t.nav[1]:t.nav[4],papers?t.readingIntro:t.notesIntro)+`<div class="wrap page-body" data-library="${type}"><div class="library-top"><div class="filters" role="group" aria-label="${t.tags}">${[...new Set(filters)].map((x,i)=>`<button class="filter" data-filter="${i===0?'all':papers?escape(x):i===1?'knowledge':'engineering'}" aria-pressed="${i===0}">${escape(x)}</button>`).join('')}</div>${papers?`<span class="count" data-count>${records.length} ${t.paperCount}</span>`:''}</div><div class="library-records">${records.map(x=>`<article data-record data-tags="${escape(JSON.stringify(x.tags||[]))}" data-category="${escape(x.category||'knowledge')}"><a class="note-row" href="/${x.lang}/${type}/${x.slug}/"><div><span class="eyebrow">${papers?`${escape(x.venue||x.journal||'')} ${escape(x.year||'')}`:x.test?t.testNote:escape(x.category==='engineering'?t.noteCategories[2]:t.noteCategories[1])} · ${x.lang.toUpperCase()}</span><h2>${escape(x.title)}</h2><p>${escape(x.description||'')}</p><p class="metadata">${(x.tags||[]).map(escape).join(' · ')}</p>${lang==='en'&&x.lang==='zh'?`<p class="metadata">${t.originalOnly}</p>`:''}</div></a></article>`).join('')}</div><div class="library-empty" data-library-empty ${records.length?'hidden':''}><h2>${papers?t.recentReading:t.recentNotes}</h2><p>${papers?t.emptyReading:t.emptyNotes}</p></div><p class="empty-state" data-filter-empty hidden>${t.noResults}</p>${papers?readingSkillLink(lang):''}</div>`;}
export function ai(lang,data={workflows:[],skills:[]},items=[]){const t=copy[lang];return pageHeader('TOOLS, TASKS & NOTES','AI × IC',t.aiIntro)+`<div class="wrap page-body ai-body"><section class="ai-section" id="workflows">${sectionHeader('01',t.workflowTitle)}<p class="section-intro">${t.workflowIntro}</p>${workflowGrid(lang,data,items)}</section><section class="ai-section" id="skills">${sectionHeader('02',t.skillLibrary)}<p class="section-intro">${t.skillLibraryIntro}</p>${skillCards(lang,data)}</section></div>`;}
export function skillPage(lang,document){const t=copy[lang];return pageHeader('SKILL LIBRARY',document.title,document.description)+`<div class="wrap page-body"><div class="skill-detail-actions"><a class="button primary" href="/downloads/analog-ic-notes.zip" download>${t.downloadSkill} ↓</a><a class="text-link" href="/${lang}/ai-ic/#skills">${t.backToSkills}</a></div><div class="article-layout"><article class="prose">${document.html}</article><aside class="article-sidebar"><h2>${t.skillFiles}</h2><a href="/downloads/analog-ic-notes/SKILL.md">${t.skillSource} ↗</a><a href="/downloads/analog-ic-notes/config.example.json">${t.skillConfig} ↗</a><h2 style="margin-top:2rem">${t.toc}</h2><nav>${document.toc.map(x=>`<a href="#${escape(x.id)}">${escape(x.title)}</a>`).join('')}</nav></aside></div></div>`;}
export function projects(lang,site){const t=copy[lang];return pageHeader('BUILD',t.nav[3],t.projectIntro)+`<div class="wrap page-body"><div class="featured-copy"><div><p class="eyebrow">01 · WEB TOOL</p><h2>IC Schematics Studio</h2></div><div><p>${t.studioSummary}</p><div class="project-actions"><a class="button primary" href="/${lang}/projects/ic-schematics-studio/">${t.viewProject}</a>${site.studioUrl?`<a class="text-link" href="${escape(site.studioUrl)}" target="_blank" rel="noopener noreferrer">${t.openStudio}</a>`:''}</div></div></div><a class="screenshot-frame" href="/${lang}/projects/ic-schematics-studio/"><img src="/assets/studio-editor.png" width="2557" height="1332" alt="${t.gallery[1]}" loading="lazy"></a><p class="image-caption">${t.realScreenshot}</p></div>`;}
export function studio(lang,site){const t=copy[lang],headings=[t.projectOverview,t.problem,t.capabilities,t.limitations],ids=['overview','problem','capabilities','limitations'];return pageHeader('PROJECT · WEB TOOL','IC Schematics Studio',t.studioTagline)+`<div class="wrap page-body"><div class="project-actions" style="margin-bottom:3rem">${studioAction(lang,site)}<span class="status">${t.evolving}</span></div><div class="article-layout"><article class="prose"><h2 id="overview" style="margin-top:0">${t.projectOverview}</h2><p>${t.studioOverview}</p><h2 id="problem">${t.problem}</h2><p>${t.studioProblem}</p><h2 id="capabilities">${t.capabilities}</h2><ul>${t.studioCapabilities.map(x=>`<li>${x}</li>`).join('')}</ul><h2 id="limitations">${t.limitations}</h2><p>${t.studioLimitations}</p></article><aside class="article-sidebar"><h2>${t.toc}</h2><nav>${headings.map((x,i)=>`<a href="#${ids[i]}">${x}</a>`).join('')}<a href="#screenshots">${t.screenshots}</a></nav></aside></div><section class="gallery" id="screenshots"><h2>${t.screenshots}</h2>${['home','editor'].map((x,i)=>`<figure><img src="/assets/studio-${x}.png" width="${i?2557:2520}" height="${i?1332:1405}" alt="${t.gallery[i]}" loading="lazy"><figcaption><strong>${t.gallery[i]}</strong><span>${t.galleryDesc[i]}</span></figcaption></figure>`).join('')}<div class="gallery-grid">${['drawings','library','community'].map((x,i)=>`<figure><img src="/assets/studio-${x}.png" alt="${t.gallery[i+2]}" loading="lazy"><figcaption><strong>${t.gallery[i+2]}</strong><span>${t.galleryDesc[i+2]}</span></figcaption></figure>`).join('')}</div></section></div>`;}
export function about(lang,document){const t=copy[lang];return `<div class="about-heading wrap"><div><p class="eyebrow">ABOUT THE PERSON</p><h1>${escape(document.title||'Eularcat')}</h1><p class="lead">${escape(document.description||t.aboutTitle)}</p></div><div class="profile-art"><img src="/assets/eularcat-mark.png" width="200" height="200" alt="Eularcat"></div></div><div class="wrap page-body"><div class="article-layout about-layout"><article class="prose about-text letter-paper">${document.html}</article><aside class="article-sidebar"><h2>${t.toc}</h2><nav>${document.toc.map(x=>`<a href="#${escape(x.id)}">${escape(x.title)}</a>`).join('')}</nav></aside></div></div>`;}
function safeUrl(url){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?escape(url):'';}catch{return '';}}
export function article(item){const t=copy[item.lang],isPaper=item.type==='reading';const citation=[(item.authors||[]).join(', '),item.title,item.venue||item.journal,item.year,item.doi?'doi:'+item.doi:''].filter(Boolean).join('. ');const original=safeUrl(item.url)||(item.doi?'https://doi.org/'+encodeURIComponent(item.doi):'');
 return pageHeader(item.type.toUpperCase(),item.title,item.description||'')+`<div class="wrap page-body"><p class="metadata">${item.updated?`${t.updated} ${escape(item.updated)} · `:''}${item.readingTime} ${t.minRead} · ${escape(item.lang.toUpperCase())}</p>${item.test?`<p class="notice">${t.testNotice}</p>`:''}${item.sample?`<p class="notice">${t.sampleNotice}</p>`:''}<p class="notice" data-original-note="${item.lang}" hidden></p><div class="article-layout"><article class="prose">${item.html}</article><aside class="article-sidebar">${isPaper?`<h2>${t.metadata}</h2><dl>${[[t.authors,(item.authors||[]).join(', ')],[t.year,item.year],[t.venue,item.venue||item.journal],['DOI',item.doi],[t.tags,(item.tags||[]).join(' · ')],[t.noteLanguage,item.lang.toUpperCase()]].filter(x=>x[1]).map(([k,v])=>`<dt>${k}</dt><dd>${escape(v)}</dd>`).join('')}</dl>${original?`<a href="${original}" target="_blank" rel="noopener noreferrer">${t.originalPaper}</a>`:''}<p class="citation">${escape(citation)}</p><button data-citation="${escape(citation)}">${t.copyCitation}</button><p data-copy-status class="metadata" aria-live="polite"></p>`:''}<h2 style="margin-top:2rem">${t.toc}</h2><nav>${item.toc.map(x=>`<a class="${x.level==='h3'?'sub':''}" href="#${escape(x.id)}">${escape(x.title)}</a>`).join('')}</nav></aside></div></div>`;
}
export function searchPage(lang){const t=copy[lang];return pageHeader('SEARCH',t.search,t.searchStart)+`<div class="wrap page-body"><label class="sr-only" for="page-search">${t.searchHint}</label><input id="page-search" class="search-page-input" type="search" placeholder="${t.searchHint}" autocomplete="off"><div id="page-results" aria-live="polite"></div></div>`;}

